# Generated by Django 2.0.4 on 2018-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AddField(
            model_name='verse',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
