# Generated by Django 2.0.4 on 2018-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0002_auto_20180419_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
