# Generated by Django 2.0.4 on 2018-04-19 19:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0005_auto_20180419_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verses',
            field=ckeditor.fields.RichTextField(blank=True, null=True, unique=True, verbose_name='Стих'),
        ),
    ]
