# Generated by Django 2.0.4 on 2018-04-23 13:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0006_auto_20180419_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='verses',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, unique=True, verbose_name='Стих'),
        ),
    ]
